export const SET_AUTH = 'SET_AUTH'
export const LOGIN_URL = `${SERVER_HOST}/user/login`
export const LOGOUT_URL = `${SERVER_HOST}/user/logout`
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const SET_AUTH_FALSE = 'SET_AUTH_FALSE'
export const LOGIN_REQUEST_FAIL = 'LOGIN_REQUEST_FAIL'
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS'
export const CLEAR_REQUEST_MESSAGE = 'CLEAR_REQUEST_MESSAGE'
